# setup cmake env
set(CPPREFLECTION_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR})

set(CPPREFLECTION_ROOT_DIR ${CPPREFLECTION_CMAKE_DIR}/..)
set(CPPREFLECTION_INCLUDE_DIR ${CPPREFLECTION_ROOT_DIR}/include)
set(CPPREFLECTION_SOURCE_DIR ${CPPREFLECTION_ROOT_DIR}/src)
set(CPPREFLECTION_OUTPUT_DIR ${CMAKE_BINARY_DIR}/bin)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CPPREFLECTION_OUTPUT_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CPPREFLECTION_OUTPUT_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CPPREFLECTION_OUTPUT_DIR})
