name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        runVcpkgInstall: true

    - name: Install dependencies
      run: vcpkg install yaml-cpp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure CMake
      run: python3 ${{github.workspace}}/scripts/cmake.py

    - name: Build
      run: make -C ${{github.workspace}}/build

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-artifacts
        path: ${{github.workspace}}/build/release
