name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{runner.workspace}}/vcpkg'
        vcpkgGitCommitId: 'e9d35a26f8081ab88035a1c8d9af38c27b52d135'

    - name: Install dependencies
      run: vcpkg install yaml-cpp

    - name: Configure CMake
      run: python3 ${{github.workspace}}/scripts/cmake.py

    - name: Build
      run: make -C ${{github.workspace}}/build

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-artifacts
        path: ${{github.workspace}}/build/release
