name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            vcpkgCommitId: 253704407ae68efa37bf8f5b59b3e06dd40d3d3f
            vcpkgPath: C:/vcpkg
            vcpkgTriplet: x64-windows
          - os: ubuntu-latest
            vcpkgCommitId: 253704407ae68efa37bf8f5b59b3e06dd40d3d3f
            vcpkgPath: /usr/local/share/vcpkg
            vcpkgTriplet: x64-linux

    env:
      VCPKG_PATH: ${{ matrix.vcpkgPath }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: ${{ github.workspace }}/vcpkg
        vcpkgGitCommitId: ${{ matrix.vcpkgCommitId }}

    - name: Install dependencies
      run: vcpkg install --triplet=${{ matrix.vcpkgTriplet }} yaml-cpp

    - name: Configure CMake
      run: python3 ${{ github.workspace }}/scripts/cmake.py

    - name: Build
      run: python3 ${{ github.workspace }}/scripts/build.py

    - name: Release
      run: python3 ${{ github.workspace }}/scripts/release.py

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-artifacts
        path: ${{ github.workspace }}/build/release/
